blank_issues_enabled: false

# 设置提 issue 前的参考文档
contact_links:
  - name: HugeGraph Doc
    url: https://hugegraph.github.io/hugegraph-doc/
    about: Please search usage here before opening a new issue
